# Generated by Django 3.2.15 on 2022-09-19 20:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='student uuid')),
                ('name', models.CharField(max_length=100, verbose_name='subject name')),
                ('description', models.TextField(blank=True, max_length=400)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('requirements', models.CharField(max_length=50, verbose_name='subject requirements')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='student uuid')),
                ('email', models.EmailField(max_length=100, verbose_name='student email')),
                ('first_name', models.CharField(max_length=100, verbose_name='student first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='student first name')),
                ('options', models.ManyToManyField(related_name='students', through='students.Choice', to='students.Option')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='environment.room', verbose_name='room connected to')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.option'),
        ),
        migrations.AddField(
            model_name='choice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
