# Generated by Django 3.2.15 on 2022-11-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='priority',
            field=models.PositiveIntegerField(default=0, verbose_name='priority of the option'),
        ),
        migrations.AddField(
            model_name='choice',
            name='reserve',
            field=models.BooleanField(default=False, verbose_name='declares if the choice is a reserve'),
        ),
    ]
