# Generated by Django 3.2.15 on 2022-09-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='option',
            name='subject_code',
            field=models.CharField(blank=True, max_length=2, verbose_name='subject code'),
        ),
        migrations.AlterField(
            model_name='option',
            name='requirements',
            field=models.CharField(blank=True, max_length=50, verbose_name='subject requirements'),
        ),
    ]
