# Generated by Django 3.2.15 on 2023-02-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ignore',
            field=models.BooleanField(default=False, verbose_name='ignore student for generation'),
        ),
    ]
