# Generated by Django 3.2.15 on 2022-12-21 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_choice_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
            preserve_default=False,
        ),
    ]
