# Generated by Django 3.2.15 on 2023-03-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20230319_1517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Requirement',
        ),
    ]
