# Generated by Django 3.2.15 on 2022-11-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20220919_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='max_choices',
            field=models.IntegerField(default=4, verbose_name='max choices a student can take'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='student last name'),
        ),
    ]
