# Generated by Django 3.2.15 on 2022-11-02 20:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0001_initial'),
        ('students', '0003_auto_20221102_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinLengthValidator(0)], verbose_name='grade required')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environment.room', verbose_name='room connected to')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.option', verbose_name='subject requirement')),
            ],
        ),
    ]
