# Generated by Django 3.2.15 on 2022-12-21 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0004_alter_availableoption_option'),
        ('students', '0003_alter_choice_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='environment.room', verbose_name='room connected to'),
            preserve_default=False,
        ),
    ]
