# Generated by Django 3.2.15 on 2022-12-22 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='students.option'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='students.student'),
        ),
    ]
