# Generated by Django 3.2.15 on 2022-11-03 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='grade',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='grade required'),
        ),
    ]
