# Generated by Django 3.2.15 on 2022-12-24 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0004_alter_availableoption_option'),
        ('students', '0005_auto_20221222_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='environment.room', verbose_name='room connected to'),
        ),
    ]
