# Generated by Django 3.2.15 on 2022-12-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='max_reserves',
            field=models.IntegerField(default=2, verbose_name='max reserves a student can take'),
        ),
    ]
