# Generated by Django 3.2.15 on 2022-11-03 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0002_generationsettings'),
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inserttogether',
            options={'verbose_name_plural': 'Insert together'},
        ),
        migrations.AlterModelOptions(
            name='optionblocks',
            options={'verbose_name_plural': 'Option blocks'},
        ),
        migrations.AlterField(
            model_name='inserttogether',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environment.generationsettings', verbose_name='settings connected to'),
        ),
    ]
