# Generated by Django 3.2.15 on 2022-11-03 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_requirement_grade'),
        ('generator', '0002_auto_20221103_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='blocks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='generator.optionblocks', verbose_name='set of blocks connected to'),
        ),
        migrations.AlterField(
            model_name='block',
            name='options',
            field=models.ManyToManyField(related_name='options', to='students.Option', verbose_name='options connected to the block'),
        ),
    ]
