# Generated by Django 3.2.15 on 2022-11-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0005_auto_20221104_1005'),
        ('generator', '0003_auto_20221103_1641'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='optionblocks',
            unique_together={('room', 'title')},
        ),
    ]
