# Generated by Django 3.2.15 on 2022-11-16 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL, verbose_name='create by'),
        ),
        migrations.AddField(
            model_name='generationsettings',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='environment.room', verbose_name='room connected to'),
        ),
        migrations.AddField(
            model_name='avalilableoptionchoices',
            name='options',
            field=models.ManyToManyField(related_name='available_option_choices', through='environment.AvailableOption', to='students.Option', verbose_name='available options'),
        ),
        migrations.AddField(
            model_name='avalilableoptionchoices',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_option_choices', to='environment.room'),
        ),
        migrations.AddField(
            model_name='availableoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.option', verbose_name='option connected to'),
        ),
        migrations.AddField(
            model_name='availableoption',
            name='option_choices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environment.avalilableoptionchoices', verbose_name='available options'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('code', 'domain')},
        ),
        migrations.AlterUniqueTogether(
            name='generationsettings',
            unique_together={('room', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='availableoption',
            unique_together={('option', 'option_choices')},
        ),
    ]
