# Generated by Django 3.2.15 on 2022-11-03 16:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='name of settings')),
                ('blocks_must_align', models.BooleanField(default=False)),
                ('max_subjects_per_block', models.PositiveIntegerField(default=12, validators=[django.core.validators.MaxValueValidator(30)])),
                ('blocks', models.PositiveIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='number of option blocks')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environment.room', verbose_name='room connected to')),
            ],
        ),
    ]
