# Generated by Django 3.2.15 on 2022-11-03 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_requirement_grade'),
        ('environment', '0002_generationsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generationsettings',
            options={'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterField(
            model_name='generationsettings',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='environment.room', verbose_name='room connected to'),
        ),
        migrations.CreateModel(
            name='AvalilableOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='preset title')),
                ('options', models.ManyToManyField(to='students.Option', verbose_name='available options')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='environment.room', verbose_name='room connected to')),
            ],
        ),
    ]
