# Generated by Django 3.2.15 on 2022-11-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avalilableoptionchoices',
            unique_together={('room', 'title')},
        ),
    ]
