# Generated by Django 3.2.15 on 2023-02-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableoption',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='override title for available option'),
        ),
    ]
