# Generated by Django 3.2.15 on 2023-03-26 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0003_alter_generationsettings_max_subjects_per_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationsettings',
            name='max_subjects_per_block',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MaxValueValidator(30)]),
        ),
    ]
