# Generated by Django 3.2.15 on 2022-11-03 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0003_auto_20221103_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avalilableoptions',
            options={'verbose_name_plural': 'available options'},
        ),
        migrations.AddField(
            model_name='generationsettings',
            name='class_size',
            field=models.PositiveIntegerField(default=24, validators=[django.core.validators.MaxValueValidator(40)], verbose_name='max class size'),
        ),
        migrations.AddField(
            model_name='generationsettings',
            name='lesson_cost',
            field=models.FloatField(default=5000, verbose_name='cost per lesson'),
        ),
    ]
