# Generated by Django 3.2.15 on 2023-02-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0003_availableoption_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableoption',
            name='ebacc',
            field=models.CharField(blank=True, choices=[('1', 'Humanities'), ('2', 'Languages'), ('3', 'Sciences'), ('4', 'Vocational'), ('5', 'Not-applicable')], default='5', max_length=5, null=True),
        ),
    ]
