# Generated by Django 3.2.15 on 2022-11-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0003_auto_20221104_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generationsettings',
            name='email_domain',
        ),
        migrations.AddField(
            model_name='room',
            name='email_domain',
            field=models.CharField(blank=True, help_text='student email domain name must match this domain', max_length=50, null=True, verbose_name='email domain match'),
        ),
    ]
