# Generated by Django 3.2.15 on 2022-12-21 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_choice_student'),
        ('environment', '0003_alter_avalilableoptionchoices_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableoption',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.option', verbose_name='option connected to'),
        ),
    ]
