# Generated by Django 3.2.15 on 2022-12-29 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0004_alter_availableoption_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableoption',
            name='option_choices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_options', to='environment.avalilableoptionchoices', verbose_name='available options'),
        ),
    ]
