# Generated by Django 3.2.15 on 2022-11-10 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0004_auto_20221104_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availableoption',
            options={'verbose_name_plural': 'Available Options'},
        ),
        migrations.RemoveField(
            model_name='avalilableoptionchoices',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='options_using',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='environment.avalilableoptionchoices'),
        ),
    ]
