# Generated by Django 3.2.15 on 2022-11-10 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0005_auto_20221110_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='options_using',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='environment.avalilableoptionchoices'),
        ),
    ]
