# Generated by Django 3.2.15 on 2022-11-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0007_alter_generationsettings_room'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('code', 'domain')},
        ),
    ]
