# Generated by Django 3.2.15 on 2022-11-14 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0008_alter_room_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='name of the room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='options_using',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='environment.avalilableoptionchoices'),
        ),
    ]
